# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_criacao', models.DateTimeField(verbose_name='Data')),
                ('data_atualizacao', models.DateTimeField(verbose_name='date updated')),
                ('url', models.URLField()),
            ],
        ),
    ]
